version: "{build}"

os: Visual Studio 2019

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  SFML_DIR: C:\Libraries\SFML-2.5.1

configuration:
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\ObEngine

before_build:
  - cmd: cd C:\Libraries
  - ps: Start-FileDownload "https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip"
  - cmd: 7z.exe x SFML-2.5.1-windows-vc15-64-bit.zip
  - cmd: cd C:\projects\ObEngine
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 -DSFML_DIR=%SFML_DIR% .
  - cmd: dir

build:
  parallel: true
  project: ObEngine.sln

test: off
