#include <Bindings/tgui/tgui.hpp>

#include <sol/sol.hpp>

#include <iostream>

#include <TGUI/TGUI.hpp>

namespace obe::Bindings
{
    void LoadString(sol::state_view state)
    {
        sol::table tguiNamespace = state["tgui"].get<sol::table>();
        sol::usertype<tgui::String> bindString
            = tguiNamespace.new_usertype<tgui::String>("String", sol::call_constructor,
                sol::constructors<tgui::String(const std::string&)>());
    }
    void call_lua_func(tgui::Button* widget, sol::protected_function func)
    {
        widget->onPress([func]() {
            auto result = func();
            if (!result.valid())
            {
                auto lua_error = result.get<sol::error>();
                std::string error_str = lua_error.what();
                std::cerr << error_str << std::endl;
            }
        });
        
    }
    void IndexDevBindings(sol::state_view state)
    {
        state["tgui"] = sol::new_table();
        LoadString(state);
        state.set_function("push_to_gui", [](tgui::GuiBase* gui, tgui::Widget* widget) { gui->add(std::shared_ptr<tgui::Widget>(widget));
        });
        state.set_function("on_press", call_lua_func);
        std::cout << "Loading ClassAbsoluteOrRelativeValue" << std::endl;
        tguiBindings::LoadClassAbsoluteOrRelativeValue(state);
        std::cout << "Loading ClassBackendBase" << std::endl;
        tguiBindings::LoadClassBackendBase(state);
        std::cout << "Loading ClassBackendFontBase" << std::endl;
        tguiBindings::LoadClassBackendFontBase(state);
        std::cout << "Loading ClassBackendRenderTargetBase" << std::endl;
        tguiBindings::LoadClassBackendRenderTargetBase(state);
        std::cout << "Loading ClassBackendTextureBase" << std::endl;
        tguiBindings::LoadClassBackendTextureBase(state);
        std::cout << "Loading ClassBackendTextBase" << std::endl;
        tguiBindings::LoadClassBackendTextBase(state);
        std::cout << "Loading ClassBaseThemeLoader" << std::endl;
        tguiBindings::LoadClassBaseThemeLoader(state);
        std::cout << "Loading ClassBitmapButton" << std::endl;
        tguiBindings::LoadClassBitmapButton(state);
        std::cout << "Loading ClassBoxLayout" << std::endl;
        tguiBindings::LoadClassBoxLayout(state);
        std::cout << "Loading ClassBoxLayoutRatios" << std::endl;
        tguiBindings::LoadClassBoxLayoutRatios(state);
        std::cout << "Loading ClassBoxLayoutRenderer" << std::endl;
        tguiBindings::LoadClassBoxLayoutRenderer(state);
        std::cout << "Loading ClassButton" << std::endl;
        tguiBindings::LoadClassButton(state);
        std::cout << "Loading ClassButtonBase" << std::endl;
        tguiBindings::LoadClassButtonBase(state);
        std::cout << "Loading ClassButtonRenderer" << std::endl;
        tguiBindings::LoadClassButtonRenderer(state);
        std::cout << "Loading ClassChatBox" << std::endl;
        tguiBindings::LoadClassChatBox(state);
        std::cout << "Loading ClassChatBoxRenderer" << std::endl;
        tguiBindings::LoadClassChatBoxRenderer(state);
        std::cout << "Loading ClassCheckBox" << std::endl;
        tguiBindings::LoadClassCheckBox(state);
        std::cout << "Loading ClassCheckBoxRenderer" << std::endl;
        tguiBindings::LoadClassCheckBoxRenderer(state);
        std::cout << "Loading ClassChildWindow" << std::endl;
        tguiBindings::LoadClassChildWindow(state);
        std::cout << "Loading ClassChildWindowRenderer" << std::endl;
        tguiBindings::LoadClassChildWindowRenderer(state);
        std::cout << "Loading ClassClickableWidget" << std::endl;
        tguiBindings::LoadClassClickableWidget(state);
        std::cout << "Loading ClassColor" << std::endl;
        tguiBindings::LoadClassColor(state);
        std::cout << "Loading ClassColorPicker" << std::endl;
        tguiBindings::LoadClassColorPicker(state);
        std::cout << "Loading ClassColorPickerRenderer" << std::endl;
        tguiBindings::LoadClassColorPickerRenderer(state);
        std::cout << "Loading ClassComboBox" << std::endl;
        tguiBindings::LoadClassComboBox(state);
        std::cout << "Loading ClassComboBoxRenderer" << std::endl;
        tguiBindings::LoadClassComboBoxRenderer(state);
        std::cout << "Loading ClassContainer" << std::endl;
        tguiBindings::LoadClassContainer(state);
        std::cout << "Loading ClassCursor" << std::endl;
        tguiBindings::LoadClassCursor(state);
        std::cout << "Loading ClassCustomWidgetForBindings" << std::endl;
        tguiBindings::LoadClassCustomWidgetForBindings(state);
        std::cout << "Loading ClassDataIO" << std::endl;
        tguiBindings::LoadClassDataIO(state);
        std::cout << "Loading ClassDefaultBackendWindow" << std::endl;
        tguiBindings::LoadClassDefaultBackendWindow(state);
        std::cout << "Loading ClassDefaultThemeLoader" << std::endl;
        tguiBindings::LoadClassDefaultThemeLoader(state);
        std::cout << "Loading ClassDeserializer" << std::endl;
        tguiBindings::LoadClassDeserializer(state);
        std::cout << "Loading ClassDuration" << std::endl;
        tguiBindings::LoadClassDuration(state);
        std::cout << "Loading ClassEditBox" << std::endl;
        tguiBindings::LoadClassEditBox(state);
        std::cout << "Loading ClassEditBoxRenderer" << std::endl;
        tguiBindings::LoadClassEditBoxRenderer(state);
        std::cout << "Loading ClassException" << std::endl;
        tguiBindings::LoadClassException(state);
        std::cout << "Loading ClassFilesystem" << std::endl;
        tguiBindings::LoadClassFilesystem(state);
        std::cout << "Loading ClassFileDialog" << std::endl;
        tguiBindings::LoadClassFileDialog(state);
        std::cout << "Loading ClassFileDialogIconLoader" << std::endl;
        tguiBindings::LoadClassFileDialogIconLoader(state);
        std::cout << "Loading ClassFileDialogRenderer" << std::endl;
        tguiBindings::LoadClassFileDialogRenderer(state);
        std::cout << "Loading ClassFont" << std::endl;
        tguiBindings::LoadClassFont(state);
        std::cout << "Loading ClassGrid" << std::endl;
        tguiBindings::LoadClassGrid(state);
        std::cout << "Loading ClassGroup" << std::endl;
        tguiBindings::LoadClassGroup(state);
        std::cout << "Loading ClassGroupRenderer" << std::endl;
        tguiBindings::LoadClassGroupRenderer(state);
        std::cout << "Loading ClassGuiBase" << std::endl;
        tguiBindings::LoadClassGuiBase(state);
        std::cout << "Loading ClassHorizontalLayout" << std::endl;
        tguiBindings::LoadClassHorizontalLayout(state);
        std::cout << "Loading ClassHorizontalWrap" << std::endl;
        tguiBindings::LoadClassHorizontalWrap(state);
        std::cout << "Loading ClassKnob" << std::endl;
        tguiBindings::LoadClassKnob(state);
        std::cout << "Loading ClassKnobRenderer" << std::endl;
        tguiBindings::LoadClassKnobRenderer(state);
        std::cout << "Loading ClassLabel" << std::endl;
        tguiBindings::LoadClassLabel(state);
        std::cout << "Loading ClassLabelRenderer" << std::endl;
        tguiBindings::LoadClassLabelRenderer(state);
        std::cout << "Loading ClassLayout" << std::endl;
        tguiBindings::LoadClassLayout(state);
        std::cout << "Loading ClassLayout2d" << std::endl;
        tguiBindings::LoadClassLayout2d(state);
        std::cout << "Loading ClassListBox" << std::endl;
        tguiBindings::LoadClassListBox(state);
        std::cout << "Loading ClassListBoxRenderer" << std::endl;
        tguiBindings::LoadClassListBoxRenderer(state);
        std::cout << "Loading ClassListView" << std::endl;
        tguiBindings::LoadClassListView(state);
        std::cout << "Loading ClassListViewRenderer" << std::endl;
        tguiBindings::LoadClassListViewRenderer(state);
        std::cout << "Loading ClassMenuBar" << std::endl;
        tguiBindings::LoadClassMenuBar(state);
        std::cout << "Loading ClassMenuBarMenuPlaceholder" << std::endl;
        tguiBindings::LoadClassMenuBarMenuPlaceholder(state);
        std::cout << "Loading ClassMenuBarRenderer" << std::endl;
        tguiBindings::LoadClassMenuBarRenderer(state);
        std::cout << "Loading ClassMessageBox" << std::endl;
        tguiBindings::LoadClassMessageBox(state);
        std::cout << "Loading ClassMessageBoxRenderer" << std::endl;
        tguiBindings::LoadClassMessageBoxRenderer(state);
        std::cout << "Loading ClassOutline" << std::endl;
        tguiBindings::LoadClassOutline(state);
        std::cout << "Loading ClassPanel" << std::endl;
        tguiBindings::LoadClassPanel(state);
        std::cout << "Loading ClassPanelRenderer" << std::endl;
        tguiBindings::LoadClassPanelRenderer(state);
        std::cout << "Loading ClassPicture" << std::endl;
        tguiBindings::LoadClassPicture(state);
        std::cout << "Loading ClassPictureRenderer" << std::endl;
        tguiBindings::LoadClassPictureRenderer(state);
        std::cout << "Loading ClassProgressBar" << std::endl;
        tguiBindings::LoadClassProgressBar(state);
        std::cout << "Loading ClassProgressBarRenderer" << std::endl;
        tguiBindings::LoadClassProgressBarRenderer(state);
        std::cout << "Loading ClassRadioButton" << std::endl;
        tguiBindings::LoadClassRadioButton(state);
        std::cout << "Loading ClassRadioButtonGroup" << std::endl;
        tguiBindings::LoadClassRadioButtonGroup(state);
        std::cout << "Loading ClassRadioButtonRenderer" << std::endl;
        tguiBindings::LoadClassRadioButtonRenderer(state);
        std::cout << "Loading ClassRangeSlider" << std::endl;
        tguiBindings::LoadClassRangeSlider(state);
        std::cout << "Loading ClassRangeSliderRenderer" << std::endl;
        tguiBindings::LoadClassRangeSliderRenderer(state);
        std::cout << "Loading ClassRootContainer" << std::endl;
        tguiBindings::LoadClassRootContainer(state);
        std::cout << "Loading ClassScrollablePanel" << std::endl;
        tguiBindings::LoadClassScrollablePanel(state);
        std::cout << "Loading ClassScrollablePanelRenderer" << std::endl;
        tguiBindings::LoadClassScrollablePanelRenderer(state);
        std::cout << "Loading ClassScrollbar" << std::endl;
        tguiBindings::LoadClassScrollbar(state);
        std::cout << "Loading ClassScrollbarChildWidget" << std::endl;
        tguiBindings::LoadClassScrollbarChildWidget(state);
        std::cout << "Loading ClassScrollbarRenderer" << std::endl;
        tguiBindings::LoadClassScrollbarRenderer(state);
        std::cout << "Loading ClassSeparatorLine" << std::endl;
        tguiBindings::LoadClassSeparatorLine(state);
        std::cout << "Loading ClassSeparatorLineRenderer" << std::endl;
        tguiBindings::LoadClassSeparatorLineRenderer(state);
        std::cout << "Loading ClassSerializer" << std::endl;
        tguiBindings::LoadClassSerializer(state);
        std::cout << "Loading ClassSignal" << std::endl;
        tguiBindings::LoadClassSignal(state);
        std::cout << "Loading ClassSignalAnimation" << std::endl;
        tguiBindings::LoadClassSignalAnimation(state);
        std::cout << "Loading ClassSignalChildWindow" << std::endl;
        tguiBindings::LoadClassSignalChildWindow(state);
        std::cout << "Loading ClassSignalItem" << std::endl;
        tguiBindings::LoadClassSignalItem(state);
        std::cout << "Loading ClassSignalItemHierarchy" << std::endl;
        tguiBindings::LoadClassSignalItemHierarchy(state);
        std::cout << "Loading ClassSignalManager" << std::endl;
        tguiBindings::LoadClassSignalManager(state);
        std::cout << "Loading ClassSlider" << std::endl;
        tguiBindings::LoadClassSlider(state);
        std::cout << "Loading ClassSliderRenderer" << std::endl;
        tguiBindings::LoadClassSliderRenderer(state);
        std::cout << "Loading ClassSpinButton" << std::endl;
        tguiBindings::LoadClassSpinButton(state);
        std::cout << "Loading ClassSpinButtonRenderer" << std::endl;
        tguiBindings::LoadClassSpinButtonRenderer(state);
        std::cout << "Loading ClassSpinControl" << std::endl;
        tguiBindings::LoadClassSpinControl(state);
        std::cout << "Loading ClassSprite" << std::endl;
        tguiBindings::LoadClassSprite(state);
        std::cout << "Loading ClassSubwidgetContainer" << std::endl;
        tguiBindings::LoadClassSubwidgetContainer(state);
        std::cout << "Loading ClassSvgImage" << std::endl;
        tguiBindings::LoadClassSvgImage(state);
        std::cout << "Loading ClassTabs" << std::endl;
        tguiBindings::LoadClassTabs(state);
        std::cout << "Loading ClassTabsRenderer" << std::endl;
        tguiBindings::LoadClassTabsRenderer(state);
        std::cout << "Loading ClassTabContainer" << std::endl;
        tguiBindings::LoadClassTabContainer(state);
        std::cout << "Loading ClassText" << std::endl;
        tguiBindings::LoadClassText(state);
        std::cout << "Loading ClassTexture" << std::endl;
        tguiBindings::LoadClassTexture(state);
        std::cout << "Loading ClassTextureManager" << std::endl;
        tguiBindings::LoadClassTextureManager(state);
        std::cout << "Loading ClassTextArea" << std::endl;
        tguiBindings::LoadClassTextArea(state);
        std::cout << "Loading ClassTextAreaRenderer" << std::endl;
        tguiBindings::LoadClassTextAreaRenderer(state);
        std::cout << "Loading ClassTextStyles" << std::endl;
        tguiBindings::LoadClassTextStyles(state);
        std::cout << "Loading ClassTheme" << std::endl;
        tguiBindings::LoadClassTheme(state);
        std::cout << "Loading ClassTimer" << std::endl;
        tguiBindings::LoadClassTimer(state);
        std::cout << "Loading ClassToggleButton" << std::endl;
        tguiBindings::LoadClassToggleButton(state);
        std::cout << "Loading ClassToolTip" << std::endl;
        tguiBindings::LoadClassToolTip(state);
        std::cout << "Loading ClassTransform" << std::endl;
        tguiBindings::LoadClassTransform(state);
        std::cout << "Loading ClassTreeView" << std::endl;
        tguiBindings::LoadClassTreeView(state);
        std::cout << "Loading ClassTreeViewRenderer" << std::endl;
        tguiBindings::LoadClassTreeViewRenderer(state);
        std::cout << "Loading ClassVerticalLayout" << std::endl;
        tguiBindings::LoadClassVerticalLayout(state);
        std::cout << "Loading ClassWidget" << std::endl;
        tguiBindings::LoadClassWidget(state);
        std::cout << "Loading ClassWidgetFactory" << std::endl;
        tguiBindings::LoadClassWidgetFactory(state);
        std::cout << "Loading ClassWidgetRenderer" << std::endl;
        tguiBindings::LoadClassWidgetRenderer(state);
        std::cout << "Loading ClassEvent" << std::endl;
        tguiBindings::LoadClassEvent(state);
        std::cout << "Loading ClassFontGlyph" << std::endl;
        tguiBindings::LoadClassFontGlyph(state);
        std::cout << "Loading ClassImageLoader" << std::endl;
        tguiBindings::LoadClassImageLoader(state);
        std::cout << "Loading ClassRelativeValue" << std::endl;
        tguiBindings::LoadClassRelativeValue(state);
        std::cout << "Loading ClassRelFloatRect" << std::endl;
        tguiBindings::LoadClassRelFloatRect(state);
        std::cout << "Loading ClassRendererData" << std::endl;
        tguiBindings::LoadClassRendererData(state);
        std::cout << "Loading ClassRenderStates" << std::endl;
        tguiBindings::LoadClassRenderStates(state);
        std::cout << "Loading ClassTextureData" << std::endl;
        tguiBindings::LoadClassTextureData(state);
        std::cout << "Loading ClassTextureDataHolder" << std::endl;
        tguiBindings::LoadClassTextureDataHolder(state);
        std::cout << "Loading ClassVertex" << std::endl;
        tguiBindings::LoadClassVertex(state);
        std::cout << "Loading EnumShowAnimationType" << std::endl;
        tguiBindings::LoadEnumShowAnimationType(state);
        std::cout << "Loading EnumTextStyle" << std::endl;
        tguiBindings::LoadEnumTextStyle(state);
        std::cout << "Loading FunctionAnyCast" << std::endl;
        tguiBindings::LoadFunctionAnyCast(state);
        std::cout << "Loading FunctionIsBackendSet" << std::endl;
        tguiBindings::LoadFunctionIsBackendSet(state);
        std::cout << "Loading FunctionSetBackend" << std::endl;
        tguiBindings::LoadFunctionSetBackend(state);
        std::cout << "Loading FunctionGetBackend" << std::endl;
        tguiBindings::LoadFunctionGetBackend(state);
        std::cout << "Loading FunctionSetGlobalTextSize" << std::endl;
        tguiBindings::LoadFunctionSetGlobalTextSize(state);
        std::cout << "Loading FunctionGetGlobalTextSize" << std::endl;
        tguiBindings::LoadFunctionGetGlobalTextSize(state);
        std::cout << "Loading FunctionSetDoubleClickTime" << std::endl;
        tguiBindings::LoadFunctionSetDoubleClickTime(state);
        std::cout << "Loading FunctionGetDoubleClickTime" << std::endl;
        tguiBindings::LoadFunctionGetDoubleClickTime(state);
        std::cout << "Loading FunctionSetResourcePath" << std::endl;
        tguiBindings::LoadFunctionSetResourcePath(state);
        std::cout << "Loading FunctionGetResourcePath" << std::endl;
        tguiBindings::LoadFunctionGetResourcePath(state);
        std::cout << "Loading FunctionSetEditCursorBlinkRate" << std::endl;
        tguiBindings::LoadFunctionSetEditCursorBlinkRate(state);
        std::cout << "Loading FunctionGetEditCursorBlinkRate" << std::endl;
        tguiBindings::LoadFunctionGetEditCursorBlinkRate(state);
        std::cout << "Loading FunctionReadFileToMemory" << std::endl;
        tguiBindings::LoadFunctionReadFileToMemory(state);
        std::cout << "Loading FunctionBindPosX" << std::endl;
        tguiBindings::LoadFunctionBindPosX(state);
        std::cout << "Loading FunctionBindPosY" << std::endl;
        tguiBindings::LoadFunctionBindPosY(state);
        std::cout << "Loading FunctionBindLeft" << std::endl;
        tguiBindings::LoadFunctionBindLeft(state);
        std::cout << "Loading FunctionBindTop" << std::endl;
        tguiBindings::LoadFunctionBindTop(state);
        std::cout << "Loading FunctionBindWidth" << std::endl;
        tguiBindings::LoadFunctionBindWidth(state);
        std::cout << "Loading FunctionBindHeight" << std::endl;
        tguiBindings::LoadFunctionBindHeight(state);
        std::cout << "Loading FunctionBindInnerWidth" << std::endl;
        tguiBindings::LoadFunctionBindInnerWidth(state);
        std::cout << "Loading FunctionBindInnerHeight" << std::endl;
        tguiBindings::LoadFunctionBindInnerHeight(state);
        std::cout << "Loading FunctionBindRight" << std::endl;
        tguiBindings::LoadFunctionBindRight(state);
        std::cout << "Loading FunctionBindBottom" << std::endl;
        tguiBindings::LoadFunctionBindBottom(state);
        std::cout << "Loading FunctionBindPosition" << std::endl;
        tguiBindings::LoadFunctionBindPosition(state);
        std::cout << "Loading FunctionBindSize" << std::endl;
        tguiBindings::LoadFunctionBindSize(state);
        std::cout << "Loading FunctionBindInnerSize" << std::endl;
        tguiBindings::LoadFunctionBindInnerSize(state);
        std::cout << "Loading FunctionBindMin" << std::endl;
        tguiBindings::LoadFunctionBindMin(state);
        std::cout << "Loading FunctionBindMax" << std::endl;
        tguiBindings::LoadFunctionBindMax(state);
        std::cout << "Loading FunctionIsWhitespace" << std::endl;
        tguiBindings::LoadFunctionIsWhitespace(state);
    }
}