#include <../Core/Bindings/Config.hpp>
#include <../Core/Bindings/Exceptions.hpp>
#include <../Core/Bindings/Patches.hpp>
#include <../Core/Bindings/obe/Animation/Animation.hpp>
#include <../Core/Bindings/obe/Animation/Easing/Easing.hpp>
#include <../Core/Bindings/obe/Animation/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Audio/Audio.hpp>
#include <../Core/Bindings/obe/Audio/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Bindings/Bindings.hpp>
#include <../Core/Bindings/obe/Bindings/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Collision/Collision.hpp>
#include <../Core/Bindings/obe/Collision/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Component/Component.hpp>
#include <../Core/Bindings/obe/Component/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Config/Config.hpp>
#include <../Core/Bindings/obe/Config/Templates/Templates.hpp>
#include <../Core/Bindings/obe/Config/Validators/Validators.hpp>
#include <../Core/Bindings/obe/Debug/Debug.hpp>
#include <../Core/Bindings/obe/Debug/Render/Render.hpp>
#include <../Core/Bindings/obe/Engine/Engine.hpp>
#include <../Core/Bindings/obe/Engine/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Event/Event.hpp>
#include <../Core/Bindings/obe/Event/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Events/Actions/Actions.hpp>
#include <../Core/Bindings/obe/Events/Cursor/Cursor.hpp>
#include <../Core/Bindings/obe/Events/Game/Game.hpp>
#include <../Core/Bindings/obe/Events/Keys/Keys.hpp>
#include <../Core/Bindings/obe/Events/Network/Network.hpp>
#include <../Core/Bindings/obe/Events/Scene/Scene.hpp>
#include <../Core/Bindings/obe/Graphics/Canvas/Canvas.hpp>
#include <../Core/Bindings/obe/Graphics/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Graphics/Graphics.hpp>
#include <../Core/Bindings/obe/Graphics/Shapes/Shapes.hpp>
#include <../Core/Bindings/obe/Graphics/Utils/Utils.hpp>
#include <../Core/Bindings/obe/Input/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Input/Input.hpp>
#include <../Core/Bindings/obe/Network/Network.hpp>
#include <../Core/Bindings/obe/Scene/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Scene/Scene.hpp>
#include <../Core/Bindings/obe/Script/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Script/Script.hpp>
#include <../Core/Bindings/obe/Script/ViliLuaBridge/ViliLuaBridge.hpp>
#include <../Core/Bindings/obe/System/Constraints/Constraints.hpp>
#include <../Core/Bindings/obe/System/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/System/Package/Package.hpp>
#include <../Core/Bindings/obe/System/System.hpp>
#include <../Core/Bindings/obe/System/Workspace/Workspace.hpp>
#include <../Core/Bindings/obe/Tiles/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Tiles/Tiles.hpp>
#include <../Core/Bindings/obe/Time/Time.hpp>
#include <../Core/Bindings/obe/Transform/Exceptions/Exceptions.hpp>
#include <../Core/Bindings/obe/Transform/Transform.hpp>
#include <../Core/Bindings/obe/Types/Types.hpp>
#include <../Core/Bindings/obe/Utils/Exec/Exec.hpp>
#include <../Core/Bindings/obe/Utils/File/File.hpp>
#include <../Core/Bindings/obe/Utils/Math/Math.hpp>
#include <../Core/Bindings/obe/Utils/String/String.hpp>
#include <../Core/Bindings/obe/Utils/Vector/Vector.hpp>
#include <../Core/Bindings/obe/obe.hpp>
#include <../Core/Bindings/vili/exceptions/exceptions.hpp>
#include <../Core/Bindings/vili/parser/parser.hpp>
#include <../Core/Bindings/vili/parser/rules/rules.hpp>
#include <../Core/Bindings/vili/utils/string/string.hpp>
#include <../Core/Bindings/vili/vili.hpp>
#include <../Core/Bindings/vili/writer/writer.hpp>
#include <sol/sol.hpp>
namespace obe::Bindings
{
    void IndexCoreBindings(sol::state_view state)
    {
    }
}