#include <Bindings/tgui/tgui.hpp>

#include <../../tgui/include/TGUI/Event.hpp>

#include <Bindings/Config.hpp>

namespace tgui::Bindings
{
    void LoadEnumKeyboardKey(sol::state_view state)
    {
        sol::table tguiNamespace = state["tgui"].get<sol::table>();
        tguiNamespace.new_enum<tgui::Event::KeyboardKey>("KeyboardKey",
            { { "Unknown", tgui::Event::KeyboardKey::Unknown },
                { "A", tgui::Event::KeyboardKey::A }, { "B", tgui::Event::KeyboardKey::B },
                { "C", tgui::Event::KeyboardKey::C }, { "D", tgui::Event::KeyboardKey::D },
                { "E", tgui::Event::KeyboardKey::E }, { "F", tgui::Event::KeyboardKey::F },
                { "G", tgui::Event::KeyboardKey::G }, { "H", tgui::Event::KeyboardKey::H },
                { "I", tgui::Event::KeyboardKey::I }, { "J", tgui::Event::KeyboardKey::J },
                { "K", tgui::Event::KeyboardKey::K }, { "L", tgui::Event::KeyboardKey::L },
                { "M", tgui::Event::KeyboardKey::M }, { "N", tgui::Event::KeyboardKey::N },
                { "O", tgui::Event::KeyboardKey::O }, { "P", tgui::Event::KeyboardKey::P },
                { "Q", tgui::Event::KeyboardKey::Q }, { "R", tgui::Event::KeyboardKey::R },
                { "S", tgui::Event::KeyboardKey::S }, { "T", tgui::Event::KeyboardKey::T },
                { "U", tgui::Event::KeyboardKey::U }, { "V", tgui::Event::KeyboardKey::V },
                { "W", tgui::Event::KeyboardKey::W }, { "X", tgui::Event::KeyboardKey::X },
                { "Y", tgui::Event::KeyboardKey::Y }, { "Z", tgui::Event::KeyboardKey::Z },
                { "Num0", tgui::Event::KeyboardKey::Num0 },
                { "Num1", tgui::Event::KeyboardKey::Num1 },
                { "Num2", tgui::Event::KeyboardKey::Num2 },
                { "Num3", tgui::Event::KeyboardKey::Num3 },
                { "Num4", tgui::Event::KeyboardKey::Num4 },
                { "Num5", tgui::Event::KeyboardKey::Num5 },
                { "Num6", tgui::Event::KeyboardKey::Num6 },
                { "Num7", tgui::Event::KeyboardKey::Num7 },
                { "Num8", tgui::Event::KeyboardKey::Num8 },
                { "Num9", tgui::Event::KeyboardKey::Num9 },
                { "Escape", tgui::Event::KeyboardKey::Escape },
                { "LControl", tgui::Event::KeyboardKey::LControl },
                { "LShift", tgui::Event::KeyboardKey::LShift },
                { "LAlt", tgui::Event::KeyboardKey::LAlt },
                { "LSystem", tgui::Event::KeyboardKey::LSystem },
                { "RControl", tgui::Event::KeyboardKey::RControl },
                { "RShift", tgui::Event::KeyboardKey::RShift },
                { "RAlt", tgui::Event::KeyboardKey::RAlt },
                { "RSystem", tgui::Event::KeyboardKey::RSystem },
                { "Menu", tgui::Event::KeyboardKey::Menu },
                { "LBracket", tgui::Event::KeyboardKey::LBracket },
                { "RBracket", tgui::Event::KeyboardKey::RBracket },
                { "Semicolon", tgui::Event::KeyboardKey::Semicolon },
                { "Comma", tgui::Event::KeyboardKey::Comma },
                { "Period", tgui::Event::KeyboardKey::Period },
                { "Quote", tgui::Event::KeyboardKey::Quote },
                { "Slash", tgui::Event::KeyboardKey::Slash },
                { "Backslash", tgui::Event::KeyboardKey::Backslash },
                { "Tilde", tgui::Event::KeyboardKey::Tilde },
                { "Equal", tgui::Event::KeyboardKey::Equal },
                { "Minus", tgui::Event::KeyboardKey::Minus },
                { "Space", tgui::Event::KeyboardKey::Space },
                { "Enter", tgui::Event::KeyboardKey::Enter },
                { "Backspace", tgui::Event::KeyboardKey::Backspace },
                { "Tab", tgui::Event::KeyboardKey::Tab },
                { "PageUp", tgui::Event::KeyboardKey::PageUp },
                { "PageDown", tgui::Event::KeyboardKey::PageDown },
                { "End", tgui::Event::KeyboardKey::End },
                { "Home", tgui::Event::KeyboardKey::Home },
                { "Insert", tgui::Event::KeyboardKey::Insert },
                { "Delete", tgui::Event::KeyboardKey::Delete },
                { "Add", tgui::Event::KeyboardKey::Add },
                { "Subtract", tgui::Event::KeyboardKey::Subtract },
                { "Multiply", tgui::Event::KeyboardKey::Multiply },
                { "Divide", tgui::Event::KeyboardKey::Divide },
                { "Left", tgui::Event::KeyboardKey::Left },
                { "Right", tgui::Event::KeyboardKey::Right },
                { "Up", tgui::Event::KeyboardKey::Up }, { "Down", tgui::Event::KeyboardKey::Down },
                { "Numpad0", tgui::Event::KeyboardKey::Numpad0 },
                { "Numpad1", tgui::Event::KeyboardKey::Numpad1 },
                { "Numpad2", tgui::Event::KeyboardKey::Numpad2 },
                { "Numpad3", tgui::Event::KeyboardKey::Numpad3 },
                { "Numpad4", tgui::Event::KeyboardKey::Numpad4 },
                { "Numpad5", tgui::Event::KeyboardKey::Numpad5 },
                { "Numpad6", tgui::Event::KeyboardKey::Numpad6 },
                { "Numpad7", tgui::Event::KeyboardKey::Numpad7 },
                { "Numpad8", tgui::Event::KeyboardKey::Numpad8 },
                { "Numpad9", tgui::Event::KeyboardKey::Numpad9 },
                { "F1", tgui::Event::KeyboardKey::F1 }, { "F2", tgui::Event::KeyboardKey::F2 },
                { "F3", tgui::Event::KeyboardKey::F3 }, { "F4", tgui::Event::KeyboardKey::F4 },
                { "F5", tgui::Event::KeyboardKey::F5 }, { "F6", tgui::Event::KeyboardKey::F6 },
                { "F7", tgui::Event::KeyboardKey::F7 }, { "F8", tgui::Event::KeyboardKey::F8 },
                { "F9", tgui::Event::KeyboardKey::F9 }, { "F10", tgui::Event::KeyboardKey::F10 },
                { "F11", tgui::Event::KeyboardKey::F11 }, { "F12", tgui::Event::KeyboardKey::F12 },
                { "F13", tgui::Event::KeyboardKey::F13 }, { "F14", tgui::Event::KeyboardKey::F14 },
                { "F15", tgui::Event::KeyboardKey::F15 },
                { "Pause", tgui::Event::KeyboardKey::Pause } });
    }
};