name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'include'
          - 'src'

    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
