name: Obidog
on:
  issue_comment:
    types: [created, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '!obidog'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GHCR_TOKEN }}'

      - uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'
        with:
          fetch-depth: 0

      - run: docker run -e OBENGINE_GIT_DIRECTORY=/obengine -v ${PWD}:/obengine --user 1000:1000 ghcr.io/obengine/obidog:1.0.0 bindings
        if: steps.check.outputs.triggered == 'true'

      - uses: actions/github-script@v5
        if: steps.check.outputs.triggered == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Obidog running...'
            })
